name: eimunisasi_nakes
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+5

environment:
  sdk: ">=3.2.0 <3.6.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # packages
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  formz: ^0.8.0
  keyboard_dismisser: ^3.0.0
  country_code_picker: ^3.1.0
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.1.0
  cached_network_image: ^3.2.0
  qr_code_scanner: ^1.0.1
  fl_chart: ^0.69.2
  math_expressions: ^2.3.0
  table_calendar: ^3.0.6
  date_time_picker: ^2.1.0
  url_launcher: ^6.1.5
  image_picker: ^1.1.2
  go_router: ^14.2.7
  # SUPABASE
  supabase_flutter: ^2.8.0
  injectable: ^2.4.4
  get_it: ^7.7.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  plugin_platform_interface: ^2.1.8
  url_launcher_platform_interface: ^2.3.2
  mocktail: ^1.0.4
  mock_supabase_http_client: ^0.0.3+1
  mock_exceptions: ^0.8.2
  injectable_generator: ^2.6.2
  bloc_test: ^9.1.7
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic
